import { type FormEvent, useState } from "react";
import type { AdminOverviewResponse, AdminSettingsResponse, MediaOrder, UpdateAdminSettingsBody } from "@cloudframe/shared";
import { PageHeader } from "./requests";
import { AlertTriangleIcon, CheckCircle2Icon, Clock3Icon, DatabaseIcon, LogOutIcon, ShieldCheckIcon } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { IndexStatus } from "./index-status";

export function Settings({ value, overview, onSave, onRotate, onLogout }: {
  value: AdminSettingsResponse;
  overview: AdminOverviewResponse;
  onSave(value: UpdateAdminSettingsBody): Promise<void>;
  onRotate(current: string, next: string): Promise<void>;
  onLogout(): Promise<void>;
}) {
  const indexHealth = value.indexHealth ?? { totalNodeCount: 0, availableNodeCount: 0, indexingSourceCount: 0, estimatedFirestoreDocumentCount: 0 };
  const [allowed, setAllowed] = useState(value.allowNewDeviceRequests);
  const [order, setOrder] = useState<MediaOrder>(value.defaultMediaOrder);
  const [seconds, setSeconds] = useState(value.defaultSlideshowSeconds.toString());
  const [current, setCurrent] = useState(""); const [next, setNext] = useState("");
  const [pending, setPending] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const save = async (event: FormEvent) => { event.preventDefault(); setPending("defaults"); setError(""); try { await onSave({ allowNewDeviceRequests: allowed, defaultMediaOrder: order, defaultSlideshowSeconds: Number(seconds) }); setMessage("Household defaults saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Settings could not be saved."); } finally { setPending(""); } };
  const rotate = async (event: FormEvent) => { event.preventDefault(); if (current.length < 16 || next.length < 16) { setError("Both passphrases must be at least 16 characters."); return; } setPending("passphrase"); setError(""); try { await onRotate(current, next); setCurrent(""); setNext(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Passphrase could not be changed."); } finally { setPending(""); } };
  const sourceErrors = overview.sources.filter(source => source.indexState.kind === "quota-exhausted" || source.indexState.kind === "provider-error" || source.indexState.kind === "reauth-required");
  return <section className="flex flex-col gap-5"><PageHeader eyebrow="Household" title="Settings" description="Set enrollment and playback defaults, review service health, and protect admin access." />
    {message && <Alert className="notice success" role="status"><CheckCircle2Icon /><AlertDescription>{message}</AlertDescription></Alert>}{error && <Alert variant="destructive"><AlertTriangleIcon /><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="settings-grid"><form className="settings-card" onSubmit={save}><CardHeader><CardTitle>Household defaults</CardTitle><CardDescription>Enrollment and playback choices inherited by televisions.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="toggle-row"><span><label htmlFor="allow-device-requests"><strong>Allow new device requests</strong></label><small id="allow-device-requests-help">Unapproved televisions can request access for 30 minutes.</small></span><input id="allow-device-requests" aria-describedby="allow-device-requests-help" type="checkbox" checked={allowed} onChange={event => setAllowed(event.target.checked)} /></div><label className="field">Default ordering<select value={order} onChange={event => setOrder(event.target.value as MediaOrder)}><option value="captured-desc">Newest captured first</option><option value="captured-asc">Oldest captured first</option><option value="name-asc">Name A–Z</option></select></label><label className="field">Default slideshow seconds<input type="number" min="1" max="3600" value={seconds} onChange={event => setSeconds(event.target.value)} /></label></CardContent><CardFooter><Button disabled={pending === "defaults"}>{pending === "defaults" ? "Saving…" : "Save defaults"}</Button></CardFooter></form>
      <Card className="library-health-ledger"><CardHeader><CardTitle className="flex items-center gap-2"><DatabaseIcon className="size-4" />Library health</CardTitle><CardDescription>Normalized indexing truth across every connected account.</CardDescription></CardHeader><CardContent><div className="metric-grid"><div><strong>{indexHealth.totalNodeCount}</strong><span>Indexed nodes</span></div><div><strong>{indexHealth.availableNodeCount}</strong><span>Available nodes</span></div><div><strong>{indexHealth.indexingSourceCount}</strong><span>Indexing sources</span></div><div><strong>{sourceErrors.length}</strong><span>Needs attention</span></div></div><div className="health-state-list">{overview.sources.length ? overview.sources.map(source => <div key={source.id}><p className="mb-2 text-sm font-medium">{source.accountLabel}</p><IndexStatus state={source.indexState} />{source.indexState.kind === "quota-exhausted" && <p className="operational-note">Recovery requires Firestore quota headroom: enable billing or reduce the selected library, then retry indexing. Billing dashboards remain authoritative.</p>}</div>) : <p className="healthy-copy inline-flex items-center gap-2"><CheckCircle2Icon className="size-4 text-emerald-600" />Connect a source to begin a household program.</p>}</div><p className="estimate mt-3"><strong>{indexHealth.estimatedFirestoreDocumentCount}</strong> Estimated Firestore documents. This estimate is operational context, not a success signal.</p></CardContent></Card>
      <Card className="bg-primary/[.035]"><CardHeader><CardTitle className="flex items-center gap-2"><Clock3Icon className="size-4" />Sync cadence</CardTitle><CardDescription>Daily deployment schedule</CardDescription></CardHeader><CardContent><p className="text-sm text-muted-foreground">This deployment uses a daily scheduled sync on Vercel Hobby. Use Sync now after important cloud changes; higher tiers can run more frequently.</p></CardContent></Card>
      <form className="settings-card border-destructive/30" onSubmit={rotate}><CardHeader><CardTitle className="flex items-center gap-2 text-destructive"><ShieldCheckIcon className="size-4" />Change passphrase</CardTitle><CardDescription>Changing it signs out every admin session, including this one.</CardDescription></CardHeader><CardContent className="grid gap-4"><label className="field">Current passphrase<input type="password" autoComplete="current-password" value={current} onChange={event => setCurrent(event.target.value)} /></label><label className="field">New passphrase<input type="password" autoComplete="new-password" value={next} onChange={event => setNext(event.target.value)} /></label></CardContent><CardFooter><Button variant="destructive" disabled={pending === "passphrase"}>{pending === "passphrase" ? "Changing…" : "Change passphrase"}</Button></CardFooter></form>
    </div><Card><CardHeader><CardTitle>Admin session</CardTitle><CardDescription>Sign out of this browser without affecting approved televisions.</CardDescription></CardHeader><CardFooter><Button variant="outline" onClick={() => void onLogout()}><LogOutIcon data-icon="inline-start" />Sign out</Button></CardFooter></Card>
  </section>;
}
