import { access, readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

const readJson = async (path: string) => JSON.parse(await readFile(path, "utf8"));

describe("Astryx foundation", () => {
  it("pins one shared Astryx 0.5.1 theme foundation", async () => {
    const root = await readJson("package.json");
    const admin = await readJson("apps/admin/package.json");
    const tv = await readJson("apps/tv/package.json");
    const theme = await readJson("packages/theme/package.json");

    expect(root.devDependencies["@astryxdesign/cli"]).toBe("0.5.1");
    expect(theme.dependencies).toMatchObject({
      "@astryxdesign/core": "0.5.1",
      "@astryxdesign/theme-neutral": "0.5.1",
      "@stylexjs/stylex": "0.19.0"
    });
    expect(admin.dependencies["@cloudframe/theme"]).toBe("*");
    expect(tv.dependencies["@cloudframe/theme"]).toBe("*");
    expect(root.scripts["build:theme"]).toContain("astryx theme build");
    expect(root.scripts["check:theme"]).toContain("--check");
  });

  it("defines Cloudframe Night by extending Astryx Neutral", async () => {
    const source = await readFile("packages/theme/src/cloudframe-night.ts", "utf8");

    expect(source).toContain("defineTheme");
    expect(source).toContain("neutralTheme");
    expect(source).toContain('name: "cloudframe-night"');
    expect(source).toContain("extends: neutralTheme");
    expect(source).toContain('"--color-background-body"');
    expect(source).toContain('"--color-background-surface"');
    expect(source).toContain('"--color-text-primary"');
    expect(source).toContain('"--color-text-secondary"');
  });

  it("keeps committed theme outputs reproducible", async () => {
    for (const path of [
      "packages/theme/dist/cloudframe-night.css",
      "packages/theme/dist/cloudframe-night.js",
      "packages/theme/dist/cloudframe-night.d.ts"
    ]) {
      await expect(access(path), path).resolves.toBeUndefined();
    }

    const css = await readFile("packages/theme/dist/cloudframe-night.css", "utf8");
    const built = await readFile("packages/theme/dist/cloudframe-night.js", "utf8");
    expect(css).toContain("@generated by `astryx theme build`");
    expect(css).toContain('data-astryx-theme="cloudframe-night"');
    expect(built).toContain("__built: true");
  });

  it("loads Astryx base styles in both application entries", async () => {
    for (const path of ["apps/admin/src/main.tsx", "apps/tv/src/main.tsx"]) {
      const entry = await readFile(path, "utf8");
      expect(entry, path).toContain('import "@astryxdesign/core/reset.css";');
      expect(entry, path).toContain('import "@astryxdesign/core/astryx.css";');
    }
  });
});
