import { access, readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import {
  resolveDarkFunctions,
  transformTvAstryxCss,
  unScopeThemeCss
} from "../scripts/astryx-css-compat.mjs";

describe("Chromium 108 Astryx CSS compatibility", () => {
  it("resolves nested light-dark expressions to their dark branch", () => {
    expect(resolveDarkFunctions("light-dark(#fff, rgb(1, 2, 3))")).toBe("rgb(1, 2, 3)");
    expect(resolveDarkFunctions("0 2px light-dark(rgb(1, 1, 1), light-dark(#222, #333))"))
      .toBe("0 2px #333");
  });

  it("removes theme scopes and roots their selectors to the TV theme", () => {
    const source = `
@scope ([data-astryx-theme="cloudframe-night"]) to ([data-astryx-theme]) {
  :scope { color: white; }
  :where(h1, h2) { margin: 0; }
  .astryx-button.primary { color: black; }
}`;

    const output = unScopeThemeCss(source, '[data-astryx-theme="cloudframe-night"]');
    expect(output).not.toContain("@scope");
    expect(output).toContain('[data-astryx-theme="cloudframe-night"] { color: white; }');
    expect(output).toContain('[data-astryx-theme="cloudframe-night"] :where(h1, h2)');
    expect(output).toContain('[data-astryx-theme="cloudframe-night"] .astryx-button.primary');
  });

  it("resolves supported sRGB color mixes from the dark theme token map", () => {
    const output = transformTvAstryxCss({
      coreCss: ".button { color: color-mix(in srgb, var(--color-accent), var(--color-tint-hover) 25%); }",
      themeCss: `@scope ([data-astryx-theme="cloudframe-night"]) to ([data-astryx-theme]) {
        :scope { --color-accent: #4080C0; --color-tint-hover: white; }
      }`
    });

    expect(output).toContain("color: #70A0D0;");
    expect(output).not.toContain("color-mix(");
  });

  it("roots generated theme globals to Cloudframe Night", () => {
    const output = transformTvAstryxCss({
      coreCss: ".core { color: light-dark(red, blue); }",
      themeCss: `@layer astryx-theme {
        :root { color-scheme: light dark; }
        html[data-theme="dark"] { color-scheme: dark; }
        @scope ([data-astryx-theme="cloudframe-night"]) to ([data-astryx-theme]) {
          :scope { --color-accent: #62AFFF; }
        }
      }`
    });

    expect(output).not.toMatch(/(?:^|[,{])\s*:root\b/m);
    expect(output).not.toContain("html[data-theme");
    expect(output).toContain('[data-astryx-theme="cloudframe-night"] { color-scheme: dark; }');
  });

  it("is deterministic and fails closed on unsupported CSS", () => {
    const input = {
      coreCss: ".a { color: light-dark(red, blue); }",
      themeCss: `@scope ([data-astryx-theme="cloudframe-night"]) to ([data-astryx-theme]) {
        :scope { --color-accent: #62AFFF; }
      }`
    };
    expect(transformTvAstryxCss(input)).toBe(transformTvAstryxCss(input));
    expect(() => resolveDarkFunctions("light-dark(red)")).toThrow(/light-dark/);
    expect(() => transformTvAstryxCss({
      ...input,
      coreCss: ".a { color: color-mix(in oklch, red, blue); }"
    })).toThrow(/Unsupported color-mix/);
    expect(() => transformTvAstryxCss({
      ...input,
      coreCss: ".a { color: color-mix(in srgb, var(--missing), white); }"
    })).toThrow(/Unable to resolve/);
    expect(() => transformTvAstryxCss({
      ...input,
      coreCss: ".a { color: rgb(1x, 2, 3); background: color-mix(in srgb, rgb(1x, 2, 3), white); }"
    })).toThrow(/Invalid RGB/);
  });

  it("ships one transformed stylesheet without unsupported expressions", async () => {
    const path = "packages/theme/dist/cloudframe-night.tv.css";
    await expect(access(path)).resolves.toBeUndefined();
    const css = await readFile(path, "utf8");
    expect(css).toContain("@generated by `node scripts/build-tv-astryx-css.mjs`");
    expect(css).toContain('[data-astryx-theme="cloudframe-night"]');
    expect(css).not.toContain("light-dark(");
    expect(css).not.toContain("color-mix(");
    expect(css).not.toContain("@scope");
    expect(css).not.toContain(":popover-open");
    expect(css).not.toContain("anchor-name:");
    expect(css).not.toContain("position-anchor:");
    expect(css).not.toMatch(/\banchor(?:-size)?\s*\(/);

    const vite = await readFile("apps/tv/vite.config.ts", "utf8");
    expect(vite).toContain('"@astryxdesign/core/astryx.css"');
    expect(vite).toContain("cloudframe-night.tv.css");
    const themePackage = JSON.parse(await readFile("packages/theme/package.json", "utf8"));
    expect(themePackage.exports["./cloudframe-night.tv.css"])
      .toBe("./dist/cloudframe-night.tv.css");
  });
});
